# Generated by Django 3.2 on 2022-05-12 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_cca_pic_courseprofileinfo_course_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprofileinfo',
            name='course_pic',
        ),
    ]
