# Generated by Django 3.2 on 2022-05-12 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_courseprofileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseprofileinfo',
            old_name='cca_pic',
            new_name='course_pic',
        ),
    ]
